sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler
script:
  - bash deploy.sh --source-only

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && bash deploy.sh
